cmake_minimum_required(VERSION 3.0.2)
project(qpoases_vendor)
find_package(catkin REQUIRED)
catkin_package(INCLUDE_DIRS include LIBRARIES qpOASES)
file(GLOB QPOASES_SRC vendor/src/*.cpp)
add_library(qpOASES SHARED ${QPOASES_SRC})
target_compile_definitions(qpOASES PRIVATE __NO_COPYRIGHT__)
target_include_directories(qpOASES PUBLIC include/qpoases_vendor)
install(TARGETS qpOASES LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION})
install(DIRECTORY include/ DESTINATION ${CATKIN_GLOBAL_INCLUDE_DESTINATION})
